version: '3.7'
services:
  db:
    image: postgres
    ports:
      - "6432:5432"  
    environment: 
        - POSTGRES_DB=medvezhiy-ugol
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: always
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medvezhiy-ugol
      - SERVER_PORT=80
    restart: always