name: MyDeploy


on:
  push:
    branches:
      - master

jobs:
  Kill_Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh  -i private_key -o StrictHostKeyChecking=no root@94.131.97.26
      - run: ssh  -i private_key root@94.131.97.26 'docker kill backend_web_1; docker rm backend_web_1; rm -rf ~/test2dep'
  Update:
    runs-on: ubuntu-latest
    needs: [Kill_Docker]
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@94.131.97.26
      - run: ssh -i private_key root@94.131.97.26 'git clone https://github.com/yepIwt/test2dep/'
  Run:
    runs-on: ubuntu-latest
    needs: [Update]
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@94.131.97.26
      - run: ssh -i private_key root@94.131.97.26 'cd ~/test2dep; docker-compose build --no-cache; docker-compose up -d;'
  Migrations:
    runs-on: ubuntu-latest
    needs: [Run]
    steps:
      - uses: actions/checkout@v2
      - run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@94.131.97.26
      - run: ssh -i private_key root@94.131.97.26 'cd ~/test2dep; docker exec -it backend_web_1 bash; make upgrade_head'
